export const clinic = {
  name: "Harirup Dental Care",
  doctor: "Dr. Harish Khamkar",
  tagline: "Caring for Your Smile, Naturally",
  address: "Patilwada, Manchar, Maharashtra 410503",
  phoneDisplay: "+91 81492 60369",
  phoneTel: "+918149260369",
  whatsapp: "918149260369",
  email: "[info@harirupdentalcare.com]",
  hours: "Mon–Sat: [10:00 AM – 8:00 PM] · Sun: [Closed]",
  mapsLink: "https://maps.app.goo.gl/xDSEkd3igUhU8N7q6",
  reviewLinks: [
    "https://goo.gl/maps/V6cffVRMLrRqsHRj7",
    "https://goo.gl/maps/a6BriDpSiEWuH8kr8",
    "https://goo.gl/maps/faf2x1aWK9sYWTn6A",
    "https://goo.gl/maps/nK9XxYBTM1Gh3EAU8",
    "https://goo.gl/maps/BDfWRdagXRYGkeuU8",
    "https://goo.gl/maps/GFGSu45M8bD6bSpD9",
    "https://goo.gl/maps/TYZymx5oYMxMPuN2A",
    "https://goo.gl/maps/2X8VwnRmkEVGj8jw6",
  ],
};
